[global]
    workgroup = SAMBA
    security = user
    usershare allow guests = yes
    # Recommended: set logging levels as needed
    log level = 1

[files]
    path = /mnt/files
    guest ok = yes
    read only = no
    public = yes
    writable = yes